services:
  - type: web
    name: server
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server/index.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
