# fly.toml app configuration file generated for ai-assistant-worker on 2025-08-03T16:06:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-assistant-worker'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
